# Generated by Django 5.2 on 2025-05-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
